name = "800-web"
compatibility_date = "2026-06-04"

[assets]
directory = "."
not_found_handling = "single-page-application"

[[routes]]
pattern = "guangying.org"
custom_domain = true

[[routes]]
pattern = "www.guangying.org"
custom_domain = true

[[routes]]
pattern = "m.guangying.org"
custom_domain = true
